# Generated by Django 3.2.14 on 2023-09-17 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('detail', models.TextField(max_length=512, verbose_name='详细信息')),
                ('level', models.SmallIntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '临时'), (4, '正常')], default=1, verbose_name='级别')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.admin', verbose_name='负责人')),
            ],
        ),
    ]
