# Generated by Django 3.2.14 on 2023-10-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='age',
            new_name='count',
        ),
    ]
